version: '2'

networks:
  n_backend:
    driver: bridge
    name: n_backend
  n_frontend:
    driver: bridge
    name: n_frontend

services:
  s_postgresql:
    build:
      context: ./website/backend/postgresql/
    image: 'bitnami/postgresql:latest'
    networks:
      - n_backend
    environment:
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}

  s_nestjs:
    build:
      context: ./website/backend/nestjs/
    image: 's_nestjs'
    networks:
      - n_backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./website/backend/nestjs/bind:/app
    command: "sh -c '\
              npm install -g npm@8.9.0 && \
              npm i -g @nestjs/cli && \
              npm install && \
              npm run ${NEST_PHASE} \
              '"
    restart: unless-stopped

  s_vuejs:
    build:
      context: ./website/frontend/vuejs/
    image: 's_vuejs'
    networks:
      - n_backend
      - n_frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
      # TODO add frontend port (for full http / https / socket.io)
    volumes:
      - ./website/frontend/vuejs/bind:/app
    command: "sh -c '\
              npm install -g npm@8.9.0 && \
              npm install -g @vue/cli \
              npm install && \
              npm run ${VUE_PHASE} \
              '"
    restart: unless-stopped
