version: '3'

networks:
  n_backend:
    driver: bridge
    name: n_backend
  n_frontend:
    driver: bridge
    name: n_frontend

services:
  s_postgresql:
    build:
      context: ./website/backend/postgresql/
    image: 's_postgres'
    networks:
      - n_backend
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRESQL_DATABASE}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_USER=${POSTGRESQL_USERNAME}
    # volumes:
    #   - ./website/backend/postgresql/db:/bitnami/postgresql

  s_nestjs:
    build:
      context: ./website/backend/nestjs/
    image: 's_nestjs'
    networks:
      - n_backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./website/backend/nestjs/bind:/app
    command: "sh -c '\
              echo \"API_42_CLIENT_ID=$API_42_CLIENT_ID\nAPI_42_CLIENT_SECRET=$API_42_CLIENT_SECRET\nAPI_42_REDIRECT_URI=$API_42_REDIRECT_URI\n\" > src/.env && \
              npm config set fund false \
              npm i @nestjs/config && \
              npm i @nestjs/common && \
              npm i @nestjs/typeorm && \
              npm i pg && \
              npm update && \
              npm install && \
              npm run ${NEST_PHASE} \
              '"

    restart: unless-stopped
    environment:
      - API_42_CLIENT_ID=${API_42_CLIENT_ID}
      - API_42_CLIENT_SECRET=${API_42_CLIENT_SECRET}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_PORT=${POSTGRESQL_PORT}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_HOST=${POSTGRESQL_HOST}

  s_vuejs:
    build:
      context: ./website/frontend/vuejs/
    image: 's_vuejs'
    networks:
      - n_backend
      - n_frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
      # TODO add frontend port (for full http / https / socket.io)
    volumes:
      - ./website/frontend/vuejs/bind:/app
    command: "sh -c '\
              echo \"{\\\"API_42_CLIENT_ID\\\":\\\"$API_42_CLIENT_ID\\\",\\\"API_42_REDIRECT_URI\\\":\\\"$API_42_REDIRECT_URI\\\"}\" > src/env.json && \
              npm config set fund false && \
              npm update && \
              npm install && \
              npm run ${VUE_PHASE} \
              '"
    restart: unless-stopped
    environment:
      - API_42_CLIENT_ID=${API_42_CLIENT_ID}
      - API_42_REDIRECT_URI=${API_42_REDIRECT_URI}
