version: '3'

networks:
  n_backend:
    driver: bridge
    name: n_backend
  n_frontend:
    driver: bridge
    name: n_frontend

services:
  s_postgresql:
    build:
      context: ./website/backend/postgresql/
    image: 's_postgres'
    networks:
      - n_backend
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRESQL_DATABASE}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_USER=${POSTGRESQL_USERNAME}
    # volumes:
    #   - ./website/backend/postgresql/db:/bitnami/postgresql

  s_pgadmin:
    build:
      context: ./website/backend/pgadmin/
    image: 's_pgadmin'
    networks:
      - n_backend
    ports:
      - "${PGADMIN_PORT_HTTP}:${PGADMIN_PORT_HTTP}"
      # - "${PGADMIN_PORT_HTTPS}:${PGADMIN_PORT_HTTPS}"
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      - PGADMIN_ENABLE_TLS=${PGADMIN_ENABLE_TLS}

  s_nestjs:
    build:
      context: ./website/backend/nestjs/
    image: 's_nestjs'
    networks:
      - n_backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./website/backend/nestjs/bind:/app
    environment:
      - POSTGRES_PORT=${POSTGRESQL_PORT}
      - POSTGRES_USER=${POSTGRESQL_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_DATABASE}
      - POSTGRES_HOST=s_postgresql
    command: "sh -c '\
              echo \"POSTGRES_PORT=${POSTGRESQL_PORT}\\nPOSTGRES_PORT=${POSTGRESQL_PORT}\\nPOSTGRES_USER=${POSTGRESQL_USERNAME}\\nPOSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}\\nPOSTGRES_DB=${POSTGRESQL_DATABASE}\\nJWT_MAX_AGE=${JWT_MAX_AGE}\\nJWT_SECRET=`date +%s%N | cut -b10-19 | md5sum | head -c 20`\\nAPI_42_CLIENT_ID=${API_42_CLIENT_ID}\\nAPI_42_CLIENT_SECRET=${API_42_CLIENT_SECRET}\\nAPI_42_REDIRECT_URI=${API_42_REDIRECT_URI}\" > .env && \
              npm config set fund false && \
              npm install --force && \
              npm run ${NEST_PHASE} \
              '"
    restart: unless-stopped

  s_vuejs:
    build:
      context: ./website/frontend/vuejs/
    image: 's_vuejs'
    networks:
      - n_backend
      - n_frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
      # TODO add frontend port (for full http / https / socket.io)
    volumes:
      - ./website/frontend/vuejs/bind:/app
    command: "sh -c '\
              echo \"{\\\"API_42_CLIENT_ID\\\":\\\"$API_42_CLIENT_ID\\\",\\\"API_42_REDIRECT_URI\\\":\\\"$API_42_REDIRECT_URI\\\"}\" > src/env.json && \
              npm config set fund false && \
              npm install && \
              yarn run ${VUE_PHASE} \
              '"
    restart: unless-stopped
    environment:
      - API_42_CLIENT_ID=${API_42_CLIENT_ID}
      - API_42_REDIRECT_URI=${API_42_REDIRECT_URI}
